# Generated by Django 5.2.3 on 2025-06-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magtrace_api', '0002_project_labelcategory_annotation_dataset_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdefinedmodel',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='userdefinedmodel',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdefinedmodel',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdefinedmodel',
            name='custom_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userdefinedmodel',
            name='parent_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='magtrace_api.userdefinedmodel'),
        ),
        migrations.AddField(
            model_name='userdefinedmodel',
            name='performance_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userdefinedmodel',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userdefinedmodel',
            name='training_datasets',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userdefinedmodel',
            name='version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='userdefinedmodel',
            name='version_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='userdefinedmodel',
            unique_together={('project', 'name', 'version')},
        ),
    ]
