# Generated by Django 5.2.3 on 2025-06-16 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magtrace_api', '0003_alter_userdefinedmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='additional_datasets',
            field=models.ManyToManyField(blank=True, related_name='additional_training_sessions', to='magtrace_api.dataset'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='base_training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='magtrace_api.trainingsession'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='is_continued_training',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='userdefinedmodel',
            name='training_datasets',
        ),
        migrations.AddField(
            model_name='userdefinedmodel',
            name='training_datasets',
            field=models.ManyToManyField(blank=True, related_name='trained_models', to='magtrace_api.dataset'),
        ),
    ]
