# Generated by Django 5.2.3 on 2025-06-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magtrace_api', '0004_enhanced_model_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='final_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='live_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='training_logs',
            field=models.JSONField(default=list),
        ),
    ]
