# Jekyll Configuration for MagTrace Documentation
# Author: Manas Pandey

title: MagTrace
description: Magnetic Field Analysis Platform - Professional ML workflow for magnetic field data analysis
url: "https://manasp21.github.io"
baseurl: "/MagTrace"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude development files and directories from Jekyll build
exclude:
  - backend/
  - .git/
  - .gitignore
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - yarn.lock
  - requirements.txt
  - requirements-lite.txt
  - run.py
  - test_workflow.py
  - "*.pyc"
  - __pycache__/
  - "*.log"
  - .env
  - .venv/
  - venv/
  - env/

# Include only documentation and necessary files
include:
  - docs/
  - README.md

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Documentation settings
defaults:
  - scope:
      path: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# GitHub Pages settings
repository: manasp21/MagTrace
github:
  username: manasp21